name: Build

on: [push]

jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn clean install

    - uses: actions/upload-artifact@master
      with:
        name: welk-lidwoord-for-windows
        path: target/Welk-Lidwoord.jar

  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

      - uses: actions/upload-artifact@master
        with:
          name: welk-lidwoord-for-ubuntu
          path: target/Welk-Lidwoord.jar

  build-on-mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

      - uses: actions/upload-artifact@master
        with:
          name: welk-lidwoord-for-mac
          path: target/Welk-Lidwoord.jar
